content: |-
  {{ include "Readme.base.md" }}

  ----
  # Terraform docs (generated)

  ## Requirements

  {{ .Content }}

  

sections:
  hide:
    - requirements

output:
  file: "Readme.md"
  mode: replace
  template: |-
    {{ .Content }}
